### ISSUE TITLE
Message flow hangs inside filter when there's no mediators configured in execution path

### ISSUE THREAD

**Issue by VijithaEkanayake** [wso2-attic/product-integration-server#40]
Please find the sample configurations.

@Path("/commonStocks")
@Source(interface="default")
@Service(tags = {
    "stock_info",
    "stock_update"
}, description = "Rest api for get stocks details", produces = MediaType.APPLICATION_JSON)
package com.sample;

constant endpoint stockEP = new EndPoint("http://localhost:8080/stockquote/all");

@GET
@PUT
@POST
@Path("/getStocksWithHeader")
resource filter(message m) {
    message response;
    log(level="custom", status="Message Received...");
    if (eval("$header.exchange", m) == "NYSE") {
          log(level="custom", status="Exchange NYSE");  
    } else {

```
}
log(level="custom", status="Message sent to Endpoint...");
response = invoke(endpointKey=stockEP, messageKey=m);
reply response;
```

}

Sample request:
curl -v http://localhost:9090/commonStocks/getStocksWithHeader

**Comment by maheshika** [comment]
Closed, since the repo is deprecated.
